spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/digitar120/service-configuration-public
          clone-on-start: true
          default-label: main
      label: main

server:
  port: 8888



